FROM ruby:3.3.11-slim
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential git libpq-dev libyaml-dev && \
    rm -rf /var/lib/apt/lists
WORKDIR /rails
ENV BUNDLE_PATH=/usr/local/bundle \
    RAILS_ENV=development
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
