services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipe_manager_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./recipe_manager
      dockerfile: Dockerfile.dev
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - ./recipe_manager:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db/recipe_manager_development
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"

volumes:
  postgres_data:
